name: github-actions-1
on: [push]
env:
  secrets.github_token: d90f2ae2ddcb5ac8810662c3c447a48944c8ef36 
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      # - run: npm install -g bats
      # - run: npm install -g eslint
      - run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          prettier: true


  # Linting:
  #   needs: check-bats-version
  #   runs-on: ubuntu-latest   
  #   steps:   
  #     - name: Run linters
  #       uses: wearerequired/lint-action@v1
  #       with:
  #         github_token: ${{ secrets.github_token }}
  #         # Enable linters
  #         eslint: true
  #         prettier: true